// Storybook-only seed data for _accounts/row.stories.tsx.
// Uses the enriched Account + Institution shapes from lib/api.ts.
// Do NOT import from this file in production page code.

import type { Account, Institution } from "@/app/lib/api";

const NOW = new Date();

function daysAgo(days: number): string {
  return new Date(NOW.getTime() - days * 86_400_000).toISOString();
}

export const seedInstitutions: Institution[] = [
  { id: 1, name: "Vanguard" },
  { id: 2, name: "Fidelity" },
  { id: 3, name: "Coinbase" },
];

export const seedAccounts: Account[] = [
  // ── Vanguard ─────────────────────────────────────────────────────────────────
  {
    id: 1,
    label: "Brokerage",
    type: "brokerage",
    currency: "USD",
    institution_id: 1,
    institution_name: "Vanguard",
    tax_treatment: "taxable",
    balance: 432_100,
    last_updated_at: daysAgo(47),
    last_update_source: "pdf",
    position_count: 4,
    classified_position_count: 4,
    class_breakdown: [
      { asset_class: "equity",       value: 353_920 },
      { asset_class: "fixed_income", value: 51_460 },
      { asset_class: "cash",         value: 26_720 },
    ],
    is_manual: false,
    is_archived: false,
    staleness_threshold_days: 30,
    is_investable: true,
  },
  {
    id: 2,
    label: "401(k)",
    type: "brokerage",
    currency: "USD",
    institution_id: 1,
    institution_name: "Vanguard",
    tax_treatment: "tax_deferred",
    balance: 142_880,
    last_updated_at: daysAgo(5),
    last_update_source: "pdf",
    position_count: 3,
    classified_position_count: 3,
    class_breakdown: [
      { asset_class: "equity",       value: 104_800 },
      { asset_class: "fixed_income", value: 38_080 },
    ],
    is_manual: false,
    is_archived: false,
    staleness_threshold_days: 30,
    is_investable: true,
  },
  {
    id: 3,
    label: "Private Equity Fund",
    type: "private",
    currency: "USD",
    institution_id: 1,
    institution_name: "Vanguard",
    tax_treatment: "taxable",
    balance: 250_000,
    last_updated_at: daysAgo(180),
    last_update_source: "manual",
    position_count: 1,
    classified_position_count: 0,
    class_breakdown: [],
    is_manual: true,
    is_archived: false,
    staleness_threshold_days: 365,
    is_investable: true,
  },
  // ── Fidelity ─────────────────────────────────────────────────────────────────
  {
    id: 4,
    label: "Checking",
    type: "bank",
    currency: "USD",
    institution_id: 2,
    institution_name: "Fidelity",
    tax_treatment: "taxable",
    balance: 24_830,
    last_updated_at: daysAgo(5),
    last_update_source: "paste",
    position_count: 1,
    classified_position_count: 1,
    class_breakdown: [{ asset_class: "cash", value: 24_830 }],
    is_manual: false,
    is_archived: false,
    staleness_threshold_days: 7,
    is_investable: true,
  },
  {
    id: 5,
    label: "HSA",
    type: "brokerage",
    currency: "USD",
    institution_id: 2,
    institution_name: "Fidelity",
    tax_treatment: "hsa",
    balance: 18_500,
    last_updated_at: daysAgo(1),
    last_update_source: "pdf",
    position_count: 3,
    classified_position_count: 3,
    class_breakdown: [
      { asset_class: "equity",       value: 11_400 },
      { asset_class: "fixed_income", value: 4_960 },
      { asset_class: "cash",         value: 2_140 },
    ],
    is_manual: false,
    is_archived: false,
    staleness_threshold_days: 30,
    is_investable: true,
  },
  {
    id: 6,
    label: "Roth IRA",
    type: "brokerage",
    currency: "USD",
    institution_id: 2,
    institution_name: "Fidelity",
    tax_treatment: "tax_free",
    balance: 189_400,
    last_updated_at: daysAgo(2),
    last_update_source: "pdf",
    position_count: 0,
    classified_position_count: 0,
    class_breakdown: [],
    is_manual: false,
    is_archived: false,
    staleness_threshold_days: 30,
    is_investable: true,
  },
  // ── Coinbase ─────────────────────────────────────────────────────────────────
  {
    id: 7,
    label: "Crypto",
    type: "crypto",
    currency: "USD",
    institution_id: 3,
    institution_name: "Coinbase",
    tax_treatment: "taxable",
    balance: 32_000,
    last_updated_at: daysAgo(3),
    last_update_source: "manual",
    position_count: 2,
    classified_position_count: 2,
    class_breakdown: [{ asset_class: "crypto", value: 32_000 }],
    is_manual: false,
    is_archived: false,
    staleness_threshold_days: 1,
    is_investable: true,
  },
  // ── Archived ─────────────────────────────────────────────────────────────────
  {
    id: 8,
    label: "Legacy Taxable (Archived)",
    type: "brokerage",
    currency: "USD",
    institution_id: 1,
    institution_name: "Vanguard",
    tax_treatment: "taxable",
    balance: 12_500,
    last_updated_at: daysAgo(90),
    last_update_source: "pdf",
    position_count: 1,
    classified_position_count: 1,
    class_breakdown: [{ asset_class: "equity", value: 12_500 }],
    is_manual: false,
    is_archived: true,
    staleness_threshold_days: 30,
    is_investable: true,
  },
];
